template = "https://github.com/giellalt/template-lang-und"
rev_id = 324
template_sha = "e348abe50c6a27ca569f7cb967cc9b3a3be7d9f9"

[replacements]
__GLOTTOLOG_ID__ = "trav1236"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-rmg"
__UND2C__ = "rmg"
__UNDEFINED__ = "Traveller Norwegian"
__UND__ = "rmg"
