template = "https://github.com/giellalt/template-lang-und"
rev_id = 320
template_sha = "67266bcec9c778bce3d70cc0a78e75bdec65cc66"

[replacements]
__GLOTTOLOG_ID__ = "trav1236"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-rmg"
__UND2C__ = "rmg"
__UNDEFINED__ = "Traveller Norwegian"
__UND__ = "rmg"
