template = "https://github.com/giellalt/template-lang-und"
rev_id = 325
template_sha = "055f523625b4faa95e2b123057d4bd9db38577ef"

[replacements]
__GLOTTOLOG_ID__ = "trav1236"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-rmg"
__UND2C__ = "rmg"
__UNDEFINED__ = "Traveller Norwegian"
__UND__ = "rmg"
